### PR TITLE
add feature: add Game result class

### PR DESCRIPTION
**Pull request by chandan-preeti12**
Plz check it sir i added game result feature

### CODE REVIEW

**Review by Chandankr19 — CHANGES_REQUESTED** [review]
plz add payment dto

**Comment by chandan-preeti12** [comment]
ok sir i will add it.

**Review by Chandankr19 — APPROVED** [review]
ok merge the features

**Comment by chandan-preeti12** [comment]
I merged the feature sir.

**Comment by Chandankr19** [comment]
Ok Great!

**Pull request merged**
